### ISSUE TITLE
Can not play Podcast - Atom RSS feed

### ISSUE THREAD

**Issue by kanyi** [raptor2101/PodCatcher#6]
I have some problem with these feeds:
http://pastebin.com/y3Gj5ZsU

any idea?

**Comment by raptor2101** [comment]
Any specific error message while opening the feed?

**Comment by kanyi** [comment]
Hi!

Where can I check the error messages? Under Openelc / Kodi.
4 other feeds is working, but these 3 problematic.
Correctly read the file, and then I have 3 empty line 4 others is working.
Nothing error messages.

Best,
Attila

2015-07-01 23:25 GMT+02:00 Christian Kölpin <notifications@github.com>:

**Comment by raptor2101** [comment]
can you manualy donwload all files containing in the feedreader folder an replace your local ones to test if my fix is working?

**Comment by kanyi** [comment]
I did. I repleaced all the files in my feedreader folder
(/storage/.kodi/addons/plugin.audio.podcatcher/feedreader)

And then restart the system.
Nothing happend. :(
I see the other podcast feeds, but not this.

2015-07-06 22:23 GMT+02:00 Christian Kölpin <notifications@github.com>:

**Comment by raptor2101** [comment]
Can you post you kodi.log (located ~home/.kodi/temp)

**Comment by kanyi** [comment]
Here it is:

http://pastebin.com/0TFLz8Ne

2015-07-07 19:00 keltezéssel, Christian Kölpin írta:

**Comment by raptor2101** [comment]
ok do the following:
* start your kodi
* open the addon
* force a refresh
* post the logfile

**Comment by kanyi** [comment]
Sorry, but I can't stop kodi. I  restarted the system.

And did what you vant. This is the log:
http://pastebin.com/NqA0e7hH


2015-07-08 20:29 GMT+02:00 Christian Kölpin <notifications@github.com>:

**Comment by raptor2101** [comment]
aaahhh you should set the type to "atom". The Plugin isn't able to autodetect the type of the podcast.

<outline text="" title="Dzsungel könyve [Tilos Rádió podcast]" type="atom" xmlUrl="https://tilos.hu/feed/show/dzsungel-konyve"/>

**Comment by kanyi** [comment]
I did.  Now it is working!  :)
Thank you.

I think it would be good to put an example file in GitHub.  It's help a lot
in the install.
